In [6]:
print("Hello world!")

Hello world!

In [7]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi

#initialize the Kaggle API
api = KaggleApi()
api.authenticate()

#define the dataset path on Kaggle
dataset_path = 'manishkc06/human-memory-and-cognition'

#define the path to download the dataset
destination_path = 'C:/Users/JB/cmps490/ml'

#download dataset
api.dataset_download_files(dataset_path, path=destination_path, unzip=True)

print(f"Dataset downloaded to: {destination_path}")

Dataset downloaded to: C:/Users/JB/cmps490/ml

In [8]:
import pandas as pd

df = pd.read_csv('C:\\Users\\JB\\cmps490\\ml\\hippoCorpusV2.csv')
df.head()

,AssignmentId,WorkTimeInSeconds,WorkerId,annotatorAge,annotatorGender,annotatorRace,distracted,draining,frequency,importance,...,mostSurprising,openness,recAgnPairId,recImgPairId,similarity,similarityReason,story,stressful,summary,timeSinceEvent
0,32RIADZISTQWI5XIVG5BN0VMYFRS4U,1641,XI8VK89S,25.0,man,white,1.0,1.0,NaN,3.0,...,when I got concert tickets,0.00,NaN,3018Q3ZVOJCZJFDMPSFXATCQ4DARA2,3.0,"I've been to a couple concerts, but not many.","Concerts are my most favorite thing, and my bo...",1.0,My boyfriend and I went to a concert together ...,90.0
1,3018Q3ZVOJCZJFDMPSFXATCQ4DARA2,1245,1HN5ZZ1D,25.0,woman,white,1.0,1.0,3.0,4.0,...,we saw the beautiful sky.,1.00,NaN,3018Q3ZVOJCZJFDMPSFXATCQ4DARA2,NaN,NaN,"The day started perfectly, with a great drive ...",1.0,My boyfriend and I went to a concert together ...,90.0
2,3IRIK4HM3B6UQBC0HI8Q5TBJZLEC61,1159,8SBPL7EI,35.0,woman,black,1.0,1.0,NaN,4.0,...,she went into labor early,0.50,NaN,3018Q3ZVOJCZJFDMPSFXATCQG04RAI,3.0,I am a mother myself,It seems just like yesterday but today makes f...,1.0,My sister gave birth to my twin niece and neph...,150.0
3,3018Q3ZVOJCZJFDMPSFXATCQG04RAI,500,M1QQED2V,30.0,woman,white,1.0,4.0,3.0,5.0,...,finding out they were healthy.,1.00,NaN,3018Q3ZVOJCZJFDMPSFXATCQG04RAI,NaN,NaN,"Five months ago, my niece and nephew were born...",2.0,My sister gave birth to my twin niece and neph...,150.0
4,3MTMREQS4W44RBU8OMP3XSK8NMJAWZ,1074,DU3RPZDB,25.0,man,white,2.0,2.0,NaN,3.0,...,When I don't answer the phone in case I owe th...,0.25,NaN,3018Q3ZVOJCZJFDMPSFXATCQG06AR3,4.0,Because I also have money problems,About a month ago I went to burning man. I was...,4.0,It is always a journey for me to go to burning...,30.0

In [9]:
df.tail()

,AssignmentId,WorkTimeInSeconds,WorkerId,annotatorAge,annotatorGender,annotatorRace,distracted,draining,frequency,importance,...,mostSurprising,openness,recAgnPairId,recImgPairId,similarity,similarityReason,story,stressful,summary,timeSinceEvent
6849,3SKEMFQBZ4RZDN7C2AMMDQKHCV68K1,926,KVSO6L8P,30.0,woman,other,3.0,5.0,3.0,5.0,...,the kitten ran into my arms.,0.125,NaN,NaN,NaN,NaN,My dog was diagnosed with lymphoma a year ago ...,5.0,"My dog, who had lymphoma, was suffering so I h...",150.0
6850,39PAAFCODNMWRITC4CBO6VRL6O4TV3,3044,QJB7AXPP,18.0,woman,asian,4.0,2.0,4.0,2.0,...,when i encountered an guy who was really scared,-0.500,NaN,NaN,NaN,NaN,"Over my vacation from my job, I went to Casper...",5.0,"On vacation, a side job was taken to plan an e...",570.0
6851,3FE2ERCCZYU396R8MJGQ6TWGLSMOPR,1008,IJP8D12L,35.0,man,asian,1.0,2.0,2.0,4.0,...,a lot of people got in the pool.,0.500,NaN,NaN,NaN,NaN,This event was a birthday party for my nephew....,2.0,This was a birthday party for my nephew that h...,21.0
6852,3J88R45B2HKQ3F50NA3MP6N9XXKPXS,1462,LCKEHYRF,30.0,man,hisp,1.0,1.0,3.0,3.0,...,my cousin threw a tantrum in the middle of the...,0.500,NaN,NaN,NaN,NaN,This event occurred about two weeks ago. I was...,2.0,It was my little cousin's birthday and went to...,14.0
6853,3YW4XOSQKR7V5JS3X3H943670Y51UE,1662,YMC00EM1,45.0,woman,white,1.0,5.0,4.0,5.0,...,my daughter agreed for guardianship.,0.750,NaN,NaN,NaN,NaN,Over the past year I have been involved with a...,4.0,My daughter had my granddaughter removed from ...,49.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6854 entries, 0 to 6853
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AssignmentId       6854 non-null   object
 1   WorkTimeInSeconds  6854 non-null   int64
 2   WorkerId           6854 non-null   object
 3   annotatorAge       6831 non-null   float64
 4   annotatorGender    6854 non-null   object
 5   annotatorRace      6854 non-null   object
 6   distracted         6854 non-null   float64
 7   draining           6854 non-null   float64
 8   frequency          4098 non-null   float64
 9   importance         6710 non-null   float64
 10  logTimeSinceEvent  6854 non-null   float64
 11  mainEvent          6854 non-null   object
 12  memType            6854 non-null   object
 13  mostSurprising     6854 non-null   object
 14  openness           6854 non-null   float64
 15  recAgnPairId       2619 non-null   object
 16  recImgPairId       5328 non-null   object
 17  similarity         2756 non-null   float64
 18  similarityReason   2756 non-null   object
 19  story              6854 non-null   object
 20  stressful          6854 non-null   float64
 21  summary            6854 non-null   object
 22  timeSinceEvent     6854 non-null   float64
dtypes: float64(10), int64(1), object(12)
memory usage: 1.2+ MB

In [11]:
df.describe()

,WorkTimeInSeconds,annotatorAge,distracted,draining,frequency,importance,logTimeSinceEvent,openness,similarity,stressful,timeSinceEvent
count,6854.000000,6831.000000,6854.000000,6854.000000,4098.000000,6710.000000,6854.000000,6854.000000,2756.000000,6854.000000,6.854000e+03
mean,2094.556317,33.553506,1.416837,2.182521,3.646413,3.952608,7.001817,0.559400,2.916546,2.168223,2.107447e+56
std,1694.783925,10.146541,0.890806,1.310124,1.028357,1.258208,13.200108,0.416494,1.441768,1.325316,6.274173e+57
min,173.000000,18.000000,1.000000,1.000000,1.000000,1.000000,1.945910,-1.000000,1.000000,1.000000,7.000000e+00
25%,924.250000,25.000000,1.000000,1.000000,3.000000,3.000000,3.555348,0.250000,2.000000,1.000000,3.500000e+01
50%,1526.000000,30.000000,1.000000,2.000000,4.000000,4.000000,4.499810,0.625000,3.000000,2.000000,9.000000e+01
75%,2678.500000,40.000000,1.000000,3.000000,4.000000,5.000000,5.010635,0.875000,4.000000,3.000000,1.500000e+02
max,10680.000000,55.000000,5.000000,5.000000,5.000000,5.000000,136.818082,1.000000,5.000000,5.000000,2.626263e+59

These are the columns in the data:

- AssignmentId: Unique ID of this story
- WorkTimeInSeconds: Time in seconds that it took the worker to do the entire HIT (reading instructions, story writing, questions)
- WorkerId: Unique ID of the worker (random string, not MTurk worker ID)
- annotatorAge: Lower limit of the age bucket of the worker. Buckets are: 18-24, 25-29, 30-34, 35-39, 40-44, 45-49, 50-54, 55+
- annotatorGender: Gender of the worker
- annotatorRace: Race/ethnicity of the worker
- distracted: How distracted were you while writing your story? (5-point Likert)
- draining: How taxing/draining was writing for you emotionally? (5-point Likert)
- frequency: How often do you think about or talk about this event? (5-point Likert)
- importance: How impactful, important, or personal is this story/event to you? (5-point Likert)
- logTimeSinceEvent: Log of time (days) since the recalled event happened
- mainEvent: Short phrase describing the main event described
- memType: Type of story (recalled, imagined, retold) - The target variable
- mostSurprising: Short phrase describing what the most surprising aspect of the story was
- openness: Continuous variable representing the openness to experience of the worker
- recAgnPairId: ID of the recalled story that corresponds to this retold story (null for imagined stories). Group on this variable to get the recalled-retold pairs.
- recImgPairId: ID of the recalled story that corresponds to this imagined story (null for retold stories). Group on this variable to get the recalled-imagined pairs.
- similarity: How similar to your life does this event/story feel to you? (5-point Likert)
- similarityReason: Free text annotation of similarity
- story: Story about the imagined or recalled event (15-25 sentences)
- stressful: How stressful was this writing task? (5-point Likert)
- summary: Summary of the events in the story (1-3 sentences)
- timeSinceEvent: Time (number of days) since the recalled event happened

Likert scaling is a bipolar scaling method, measuring either positive or negative response to a statement.