In [1]:
print("Hello world!")

Hello world!

In [3]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi

#initialize the Kaggle API
api = KaggleApi()
api.authenticate()

#define the dataset path on Kaggle
dataset_path = 'osmi/mental-health-in-tech-survey'

#define the path to download the dataset
destination_path = 'C:/Users/JB/cmps490/ml'

#download dataset
api.dataset_download_files(dataset_path, path=destination_path, unzip=True)

print(f"Dataset downloaded to: {destination_path}")

Dataset downloaded to: C:/Users/JB/cmps490/ml

In [3]:
import pandas as pd

df = pd.read_csv('C:\\Users\\JB\\cmps490\\ml\\survey.csv')
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [4]:
df.tail()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [6]:
df.describe()

                Age
count  1.259000e+03
mean   7.942815e+07
std    2.818299e+09
min   -1.726000e+03
25%    2.700000e+01
50%    3.100000e+01
75%    3.600000e+01
max    1.000000e+11

In [9]:
print(df["comments"].value_counts())

comments
* Small family business - YMMV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                5
I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
(yes but the situation was unusual and involved a change in leadership at a very high level in the organization as well as an extended leave of absence)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
None of us who are already in marginal groups in tech--the non-young the non-male the non-white--will risk our careers to admit another source of stigma: poor health.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
I have been incredibly public about my own struggle in my own conversations and in social media insofar as how I can use my depression to raise awareness or help others. Because of that my employer - or any future employer - kind of knows by default. It's not a secret. That said the downside of that openness is that I have no faith that I wouldn't be discriminated against at a future job simply because the information is public. Likewise I worry I'm seen as less-than by my employer in some circumstances. Regerdless I don't regret being public and raising awareness. My point is that even those of us who do publicly discuss the issue fear systemic retribution.     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
In Germany your employer doesn't really provide mental health benefits. There's a standard and I get that but I would get the same at any other company in Germany.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
fwiw I am a co founder of this company and the would you X in an interview questions shouldn't reflect how I would treat anyone addressing their own phys/mental health issue to me in such a situation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
I talked to a psychiatrist once about taking medical leave for mental health issues with his referral. He was willing to help but warned me that I may not want to as he's seen that sort of thing follow people throughout their tech careers (word gets out even if it's confidential at work). I've been terrified of bringing mental health up anywhere that coworkers or potential employers could see ever since.                                                                                                                                                                                                                                                                        1
So much depends upon the organization.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Bipolar disorder                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Name: count, Length: 160, dtype: int64

In [10]:
df["obs_consequence"].value_counts()

obs_consequence
No     1075
Yes     184
Name: count, dtype: int64

In [11]:
#using dictionary to apply value_counts on each column
value_counts_per_column = {col: df[col].value_counts() for col in df}
#print value_counts for all columns
for col, counts in value_counts_per_column.items():
    print(f"Value counts for {col}:\n{counts}\n")

Value counts for Timestamp:
Timestamp
2014-08-27 12:44:51    2
2014-08-27 14:22:43    2
2014-08-27 12:31:41    2
2014-08-28 16:52:34    2
2014-08-27 17:33:52    2
                      ..
2014-08-27 15:35:21    1
2014-08-27 15:34:32    1
2014-08-27 15:34:31    1
2014-08-27 15:34:23    1
2016-02-01 23:04:31    1
Name: count, Length: 1246, dtype: int64

Value counts for Age:
Age
 29             85
 32             82
 26             75
 27             71
 33             70
 28             68
 31             67
 34             65
 30             63
 25             61
 35             55
 23             51
 24             46
 37             43
 38             39
 36             37
 40             33
 39             33
 43             28
 22             21
 41             21
 42             20
 21             16
 45             12
 46             12
 44             11
 19              9
 18              7
 48              6
 50              6
 20              6
 51              5
 49              4
 56              4
 57              3
 54              3
 55              3
 47              2
 60              2
 99999999999     1
 5               1
-1               1
 11              1
 8               1
 61              1
 53              1
-29              1
-1726            1
 65              1
 62              1
 58              1
 329             1
 72              1
Name: count, dtype: int64

Value counts for Gender:
Gender
Male                                              615
male                                              206
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Male                                                3
Woman                                               3
Cis Male                                            2
Man                                                 2
Female (trans)                                      2
Female                                              2
Trans woman                                         1
msle                                                1
male leaning androgynous                            1
Neuter                                              1
cis male                                            1
queer                                               1
Female (cis)                                        1
Mail                                                1
cis-female/femme                                    1
A little about you                                  1
Malr                                                1
p                                                   1
femail                                              1
Cis Man                                             1
Guy (-ish) ^_^                                      1
Enby                                                1
Agender                                             1
Androgyne                                           1
Male-ish                                            1
maile                                               1
Trans-female                                        1
Cis Female                                          1
something kinda male?                               1
Mal                                                 1
Male (CIS)                                          1
queer/she/they                                      1
non-binary                                          1
Femake                                              1
woman                                               1
Nah                                                 1
All                                                 1
fluid                                               1
Genderqueer                                         1
ostensibly male, unsure what that really means      1
Name: count, dtype: int64

Value counts for Country:
Country
United States             751
United Kingdom            185
Canada                     72
Germany                    45
Ireland                    27
Netherlands                27
Australia                  21
France                     13
India                      10
New Zealand                 8
Poland                      7
Switzerland                 7
Sweden                      7
Italy                       7
South Africa                6
Belgium                     6
Brazil                      6
Israel                      5
Singapore                   4
Bulgaria                    4
Austria                     3
Finland                     3
Mexico                      3
Russia                      3
Denmark                     2
Greece                      2
Colombia                    2
Croatia                     2
Portugal                    2
Moldova                     1
Georgia                     1
Bahamas, The                1
China                       1
Thailand                    1
Czech Republic              1
Norway                      1
Romania                     1
Nigeria                     1
Japan                       1
Hungary                     1
Bosnia and Herzegovina      1
Uruguay                     1
Spain                       1
Zimbabwe                    1
Latvia                      1
Costa Rica                  1
Slovenia                    1
Philippines                 1
Name: count, dtype: int64

Value counts for state:
state
CA    138
WA     70
NY     57
TN     45
TX     44
OH     30
IL     29
OR     29
PA     29
IN     27
MI     22
MN     21
MA     20
FL     15
NC     14
VA     14
WI     12
GA     12
MO     12
UT     11
CO      9
MD      8
AL      8
AZ      7
OK      6
NJ      6
KY      5
SC      5
IA      4
CT      4
DC      4
NV      3
VT      3
SD      3
KS      3
NH      3
WY      2
NM      2
NE      2
WV      1
ID      1
MS      1
RI      1
LA      1
ME      1
Name: count, dtype: int64

Value counts for self_employed:
self_employed
No     1095
Yes     146
Name: count, dtype: int64

Value counts for family_history:
family_history
No     767
Yes    492
Name: count, dtype: int64

Value counts for treatment:
treatment
Yes    637
No     622
Name: count, dtype: int64

Value counts for work_interfere:
work_interfere
Sometimes    465
Never        213
Rarely       173
Often        144
Name: count, dtype: int64

Value counts for no_employees:
no_employees
6-25              290
26-100            289
More than 1000    282
100-500           176
1-5               162
500-1000           60
Name: count, dtype: int64

Value counts for remote_work:
remote_work
No     883
Yes    376
Name: count, dtype: int64

Value counts for tech_company:
tech_company
Yes    1031
No      228
Name: count, dtype: int64

Value counts for benefits:
benefits
Yes           477
Don't know    408
No            374
Name: count, dtype: int64

Value counts for care_options:
care_options
No          501
Yes         444
Not sure    314
Name: count, dtype: int64

Value counts for wellness_program:
wellness_program
No            842
Yes           229
Don't know    188
Name: count, dtype: int64

Value counts for seek_help:
seek_help
No            646
Don't know    363
Yes           250
Name: count, dtype: int64

Value counts for anonymity:
anonymity
Don't know    819
Yes           375
No             65
Name: count, dtype: int64

Value counts for leave:
leave
Don't know            563
Somewhat easy         266
Very easy             206
Somewhat difficult    126
Very difficult         98
Name: count, dtype: int64

Value counts for mental_health_consequence:
mental_health_consequence
No       490
Maybe    477
Yes      292
Name: count, dtype: int64

Value counts for phys_health_consequence:
phys_health_consequence
No       925
Maybe    273
Yes       61
Name: count, dtype: int64

Value counts for coworkers:
coworkers
Some of them    774
No              260
Yes             225
Name: count, dtype: int64

Value counts for supervisor:
supervisor
Yes             516
No              393
Some of them    350
Name: count, dtype: int64

Value counts for mental_health_interview:
mental_health_interview
No       1008
Maybe     207
Yes        44
Name: count, dtype: int64

Value counts for phys_health_interview:
phys_health_interview
Maybe    557
No       500
Yes      202
Name: count, dtype: int64

Value counts for mental_vs_physical:
mental_vs_physical
Don't know    576
Yes           343
No            340
Name: count, dtype: int64

Value counts for obs_consequence:
obs_consequence
No     1075
Yes     184
Name: count, dtype: int64

Value counts for comments:
comments
* Small family business - YMMV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                5
I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
(yes but the situation was unusual and involved a change in leadership at a very high level in the organization as well as an extended leave of absence)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
None of us who are already in marginal groups in tech--the non-young the non-male the non-white--will risk our careers to admit another source of stigma: poor health.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
I have been incredibly public about my own struggle in my own conversations and in social media insofar as how I can use my depression to raise awareness or help others. Because of that my employer - or any future employer - kind of knows by default. It's not a secret. That said the downside of that openness is that I have no faith that I wouldn't be discriminated against at a future job simply because the information is public. Likewise I worry I'm seen as less-than by my employer in some circumstances. Regerdless I don't regret being public and raising awareness. My point is that even those of us who do publicly discuss the issue fear systemic retribution.     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
In Germany your employer doesn't really provide mental health benefits. There's a standard and I get that but I would get the same at any other company in Germany.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
fwiw I am a co founder of this company and the would you X in an interview questions shouldn't reflect how I would treat anyone addressing their own phys/mental health issue to me in such a situation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
I talked to a psychiatrist once about taking medical leave for mental health issues with his referral. He was willing to help but warned me that I may not want to as he's seen that sort of thing follow people throughout their tech careers (word gets out even if it's confidential at work). I've been terrified of bringing mental health up anywhere that coworkers or potential employers could see ever since.                                                                                                                                                                                                                                                                        1
So much depends upon the organization.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Bipolar disorder                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Name: count, Length: 160, dtype: int64